name: flutter_atm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # sort by asc
  equatable: ^2.0.3
  flutter_svg: ^1.0.0
  flutter_lorem: ^2.0.0
  faker: ^2.0.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.1.1
  persistent_bottom_nav_bar: ^4.0.2
  velocity_x: ^3.3.0
  random_string: ^2.3.1
  mock_data: ^2.0.0

  # moor
  drift: "^1.0.1"
  sqlite3_flutter_libs: "^0.5.0"
  path: "^1.8.0"

  ex_reusable:
    path: ./packages/ex_reusable

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  drift_dev: ^1.1.1
  build_runner: ^2.1.7

  #  TEST
  test: any
#  flutter_test:
#    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: ExIcons
      fonts:
        - asset: assets/fonts/ExIcons.ttf

