name: flutter_atm
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # sort by asc
#  dio: ^4.0.0
  equatable: ^2.0.3
  flutter_svg: ^0.22.0
  flutter_lorem: ^2.0.0
  faker: ^2.0.0
#  file_picker: ^4.1.6
  get: ^4.1.4
  get_storage: ^2.0.2
  google_fonts: ^2.1.0
#  group_list_view: ^1.1.1
#  image_picker: ^0.8.3
#  linkfy_text: ^1.0.4
#  open_file: ^3.2.1
#  package_info_plus: ^1.0.6
#  path_provider: ^2.0.5
  persistent_bottom_nav_bar: ^4.0.2
#  share: ^2.0.4
#  snapping_sheet: ^3.1.0
#  url_launcher: ^6.0.3
#  uuid: ^3.0.4
  velocity_x: ^3.3.0
#  vibration: ^1.7.3
#  network_info_plus: ^2.0.2
#  dart_ping: ^6.1.1
#  dart_ping_ios: ^1.0.0
#  font_awesome_flutter: ^9.2.0
#  lottie: ^1.2.1
  random_string: ^2.3.1
  mock_data: ^2.0.0
#  line_icons: ^2.0.1
#  flutter_inappwebview: ^5.3.2
#  phone_form_field: ^4.3.1

  # moor
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.0
  path: ^1.8.0

  # FIREBASE
#  fcm_config: ^3.1.2
#  firebase_core: ^1.8.0
#  firebase_auth: ^3.1.4
#  cloud_firestore: ^2.5.4
#  google_sign_in: ^5.2.0
#  flutter_signin_button: ^2.0.0
#  firebase_storage: ^8.0.0
#  ha_firestore_realtime_paginate: ^0.0.3
#  firebase_remote_config: ^1.0.2

  ex_reusable:
    path: ./packages/ex_reusable

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: ^0.9.2
  drift_dev: ^1.0.2
  build_runner: ^2.1.5

  #  TEST
  test: any
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: ExIcons
      fonts:
        - asset: assets/fonts/ExIcons.ttf

